// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: MyFirst_SquareLine_Project

#ifndef _MYFIRST_SQUARELINE_PROJECT_UI_H
#define _MYFIRST_SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdio.h>
#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void hide_keyboard_Animation(lv_obj_t * TargetObject, int delay);
void show_keyboard_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label1;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
void ui_event_Keyboard2(lv_event_t * e);
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label2;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui____initial_actions0;

extern lv_obj_t * objpg;

#define SD_PATH "/storage"




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
